rm thesis_sandipan.aux
rm thesis_sandipan.idx
rm thesis_sandipan.lof
rm thesis_sandipan.log
rm thesis_sandipan.lot
rm thesis_sandipan.out
rm thesis_sandipan.toc
pdflatex thesis_sandipan.tex 
bibtex thesis_sandipan.aux 
pdflatex thesis_sandipan.tex 
pdflatex thesis_sandipan.tex
rm thesis_sandipan.aux
